apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: innerapiclient-ingress
  namespace: innerapi
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"   # Optional: Use regex for more control
    nginx.ingress.kubernetes.io/proxy-body-size: 50m  # Adjust body size if needed
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600s"  # Adjust timeouts if needed
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600s"   # Adjust timeouts if needed
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~* \.(svg)$ {
        root /usr/share/nginx/html;
      }
spec:
  rules:
    - http:
        paths:
          - path: /innerapiclient(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: innerapiclient-service
                port:
                  number: 8080

